# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pf4Khr-gmijLA0fQyjDf5w2PAbe-9qZk
"""

import torch
from torchvision import transforms, models
from PIL import Image
import torch.nn.functional as F

# 1. Setup device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# 2. Load the saved checkpoint
checkpoint_path = '/content/drive/MyDrive/plant_vit_model.pth'  # Update if your path is different
checkpoint = torch.load(checkpoint_path, map_location=device)

class_names = checkpoint['classes']
print(f"Loaded {len(class_names)} classes successfully.")

# 3. Re-initialize the model architecture and load weights
weights = models.ViT_B_16_Weights.DEFAULT
model = models.vit_b_16(weights=weights)

# Replace the head to match your training configuration
model.heads.head = torch.nn.Linear(model.heads.head.in_features, len(class_names))

# Load the trained weights
model.load_state_dict(checkpoint['model_state_dict'])
model.to(device)
model.eval()  # Set model to evaluation mode

# 4. Define the inference transforms (must match validation preprocessing)
inference_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# 5. Function to predict a single image
def predict_image(image_path):
    # Open image and ensure it's RGB
    image = Image.open(image_path).convert('RGB')

    # Apply transforms and add batch dimension (shape: [1, 3, 224, 224])
    input_tensor = inference_transform(image).unsqueeze(0).to(device)

    # Run inference
    with torch.no_grad():
        outputs = model(input_tensor)
        probabilities = F.softmax(outputs, dim=1)
        confidence, predicted_idx = torch.max(probabilities, 1)

    predicted_label = class_names[predicted_idx.item()]
    confidence_score = confidence.item() * 100

    print(f"\n--- Prediction Results ---")
    print(f"Image: {image_path}")
    print(f"Predicted Class: {predicted_label}")
    print(f"Confidence: {confidence_score:.2f}%")

    return predicted_label, confidence_score

# --- Example Usage ---
# Replace with the path to a real test image on your machine or Colab
test_image_path = '/content/drive/MyDrive/PlantVillage/val/Strawberry___Leaf_scorch/01d11a79-f858-4e58-9b14-c3f0619af1f7___RS_L.Scorch 0090.JPG'

predict_image(test_image_path)

