# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vqSilYtLOAoOXtpqjHnekpNSHTAoLWv

## Mounting Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

# Check device availability (Make sure Runtime -> Change runtime type -> T4 GPU is selected)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

if device.type == 'cpu':
    print("WARNING: Training a Vision Transformer on CPU will be very slow. Please enable GPU in Colab runtime settings.")

# Update paths to match the extracted folder structure in Colab
# (Check your Colab file explorer on the left to verify the exact folder name)
train_dir = '/content/drive/MyDrive/PlantVillage/train'  # or check if it's directly under plantvillage_data
val_dir = '/content/drive/MyDrive/PlantVillage/val'


IMG_SIZE = 224
BATCH_SIZE = 32

train_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

train_dataset = datasets.ImageFolder(train_dir, transform=train_transforms)
val_dataset = datasets.ImageFolder(val_dir, transform=val_transforms)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

num_classes = len(train_dataset.classes)
print(f"Total Classes Found: {num_classes}")

weights = models.ViT_B_16_Weights.DEFAULT
model = models.vit_b_16(weights=weights)

# Replace the classification head
model.heads.head = nn.Linear(model.heads.head.in_features, num_classes)

model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=5)

import torch
from torch.utils.data import DataLoader
from tqdm.auto import tqdm

# 0. Hardware setup for Google Colab
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Enable cuDNN autotuner for extra speed (if input shapes are constant)
torch.backends.cudnn.benchmark = True

num_epochs = 5

# 1. OPTIMIZE DATALOADERS (Crucial for Colab)
# Make sure to set num_workers=2 (Colab standard is usually 2 vCPUs) and pin_memory=True
# train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True, num_workers=2, pin_memory=True)
# val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False, num_workers=2, pin_memory=True)

# Initialize Modern AMP Scaler (replaces deprecated torch.cuda.amp)
scaler = torch.amp.GradScaler('cuda')

for epoch in range(num_epochs):
    print(f"\nEpoch [{epoch+1}/{num_epochs}]")

    # --- TRAINING ---
    model.train()
    running_loss = 0.0
    correct_train = 0
    total_train = 0

    train_bar = tqdm(train_loader, desc="Training", leave=False)
    for inputs, labels in train_bar:
        # non_blocking=True speeds up CPU-to-GPU transfer
        inputs = inputs.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()

        # Automatic Mixed Precision Forward Pass
        with torch.amp.autocast('cuda'):
            outputs = model(inputs)
            loss = criterion(outputs, labels)

        # Scaled Backward Pass
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        # Track stats (using detach to prevent unnecessary synchronization blocks)
        running_loss += loss.item() * inputs.size(0)
        _, predicted = outputs.max(1)
        total_train += labels.size(0)
        correct_train += predicted.eq(labels).sum().item()

        current_acc = correct_train / total_train
        train_bar.set_postfix(loss=f"{loss.detach().item():.4f}", acc=f"{current_acc*100:.2f}%")

    epoch_train_loss = running_loss / total_train
    epoch_train_acc = correct_train / total_train

    # --- VALIDATION ---
    model.eval()
    val_loss = 0.0
    correct_val = 0
    total_val = 0

    val_bar = tqdm(val_loader, desc="Validation", leave=False)
    with torch.no_grad():
        for inputs, labels in val_bar:
            inputs = inputs.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            with torch.amp.autocast('cuda'):
                outputs = model(inputs)
                loss = criterion(outputs, labels)

            val_loss += loss.item() * inputs.size(0)
            _, predicted = outputs.max(1)
            total_val += labels.size(0)
            correct_val += predicted.eq(labels).sum().item()

            current_val_acc = correct_val / total_val
            val_bar.set_postfix(loss=f"{loss.item():.4f}", acc=f"{current_val_acc*100:.2f}%")

    epoch_val_loss = val_loss / total_val
    epoch_val_acc = correct_val / total_val

    scheduler.step()

    print(f"Summary -> Train Loss: {epoch_train_loss:.4f} | Train Acc: {epoch_train_acc*100:.2f}% || "
          f"Val Loss: {epoch_val_loss:.4f} | Val Acc: {epoch_val_acc*100:.2f}%")

import torch

# 1. Save the model weights and the class names dictionary together
checkpoint = {
    'model_state_dict': model.state_dict(),
    'classes': train_dataset.classes
}
torch.save(checkpoint, 'plant_vit_model.pth')

# 2. (Optional) Save the transforms if you are using a separate script for inference
# You can use libraries like dill or pickle, or simply recreate val_transforms in your inference script.

